name: Build

on: ['push']

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    env:
      IMAGE: ghcr.io/emfcamp/buildmap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ github.sha }}-${{ github.run_number }}
            ${{ env.IMAGE }}:latest
